id: I40701050
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T19:11:49+00:00'
last_modified: '2022-06-07T21:42:44.963077+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD152295
  title: 'སློབ་གྲྭ་ཆེན་མོའི་སུམ་རྟགས་སློབ་དེབ། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5B14:
      image_group_id: I2PD20388
      title: ''
      total_pages: 436
      order: 1
      base_file: 5B14.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
